package hut.tyt.pojo;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.name
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.age
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.sex
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.email
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.post_id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.department_id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.info_id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public Integer infoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.id
     *
     * @return the value of employees.id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.id
     *
     * @param id the value for employees.id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.name
     *
     * @return the value of employees.name
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.name
     *
     * @param name the value for employees.name
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.age
     *
     * @return the value of employees.age
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.age
     *
     * @param age the value for employees.age
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.sex
     *
     * @return the value of employees.sex
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.sex
     *
     * @param sex the value for employees.sex
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.email
     *
     * @return the value of employees.email
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.email
     *
     * @param email the value for employees.email
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.post_id
     *
     * @return the value of employees.post_id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.post_id
     *
     * @param postId the value for employees.post_id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.department_id
     *
     * @return the value of employees.department_id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.department_id
     *
     * @param departmentId the value for employees.department_id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.info_id
     *
     * @return the value of employees.info_id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public Integer getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.info_id
     *
     * @param infoId the value for employees.info_id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public void setInfoId(Integer infoId) {
        this.infoId = infoId;
    }

    @Override
    public String toString() {
        return id + "," + name +
                "," + age+
                "," + sex+
                "," + email+
                "," + postId +
                "," + departmentId +
                "," + infoId;
    }
}