package hut.tyt.pojo;

public class Information {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.number
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information.password
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    private Integer password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.id
     *
     * @return the value of information.id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.id
     *
     * @param id the value for information.id
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.number
     *
     * @return the value of information.number
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.number
     *
     * @param number the value for information.number
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information.password
     *
     * @return the value of information.password
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public Integer getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information.password
     *
     * @param password the value for information.password
     *
     * @mbg.generated Mon Aug 01 23:09:08 CST 2022
     */
    public void setPassword(Integer password) {
        this.password = password;
    }
}